def pendi():
    print ('________________      ')
    print ('|               |     ')
    print ('|               |     ')
    print ('|               |     ')
    print ('|               0     ')
    print ('|              /|\\    ')
    print ('|             / | \\   ')
    print ('|               |     ')
    print ('|              / \\    ')
    print ('|             /   \\   ')